name: tfsec-and-trufflehog
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec-and-trufflehog:
    name: tfsec-and-trufflehog
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.72.0
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3